id: P25175451
initial_creation_type: input
source_metadata:
  title: Religious history by Nyang ral Nyima od zer (1124–1192)
  author: ཉང་རལ་ཉི་མ་འོད་ཟེར།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-11-07);
    no page numbers, unrevised, no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by Tibet People's
    Publishing House (Xizang Renmin Chubanshe) (src)
  - Text input:unspecified
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2398
  bases:
    1ba1:
      title: Religious history by Nyang ral Nyima od zer (1124–1192)
      order: 1
      base_file: 1ba1.txt
created_at: '2022-04-15T18:29:08.400428'
last_modified_at: '2022-04-15T18:29:08.400435'
quality: null
